version: '3.9'
services:
    app:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: school
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres

        depends_on:
            - db
        volumes:
            - ./src:/src/app/nestjs/src

    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: school
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
